"use strict";
exports.__esModule = true;
var mobile_1 = require("./mobile");
var mobileLibrary_1 = require("./mobileLibrary");
var mobile1 = new mobile_1.Mobile("Nokia", "3210", "Nokia", 0, "Grey", false, 0, 50);
var mobile2 = new mobile_1.Mobile("Iphone", "3G", "Apple", 8, "Black", false, 1, 150);
var mobile3 = new mobile_1.Mobile("Samsung", "Galaxy 10", "Samsung", 128, "White", true, 5, 350);
var mobile4 = new mobile_1.Mobile("Blackview", "A20", "Blackview", 16, "Black", false, 3, 100);
var allMobiles = [mobile1, mobile2, mobile3, mobile4];
var tienda = new mobileLibrary_1.MobileLibrary("Advanced Shop", "Barcelona", allMobiles);
console.log(tienda.getName());
console.log(tienda.getLocation());
console.log(tienda.getMobiles());
console.log(tienda.getTotalPrice());
console.log("--------------------");
var allMobilesInverse = [mobile4, mobile3, mobile2, mobile1];
tienda.setName("Past shop");
tienda.setLocation("Madrid");
tienda.setMobiles(allMobilesInverse);
tienda.setTotalPrice(50);
console.log(tienda.getName());
console.log(tienda.getLocation());
console.log(tienda.getMobiles());
console.log(tienda.getTotalPrice());
console.log("--------------------");
var tienda1 = new mobileLibrary_1.MobileLibrary("Advanced Shop", "Barcelona", allMobiles);
tienda1.printLibrary();
